# arb-dir: lib/l10n
# template-arb-file: lang_en.arb
# output-localization-file: app_localizations.dart
arb-dir: lib/l10n
template-arb-file: lang_en.arb
output-dir: lib/generated
output-localization-file: l10n.dart
output-class: AppLocalizations
